import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";
import Router from "next/router";

export default function Home() {
  const [loading, setLoading] = useState(false);

  const chat = async () => {
    setLoading(true);
    const resp = await fetch("/api/chat", {
      method: "POST",
      body: JSON.stringify({
        token: localStorage.getItem("tinder_api_key"),
      }),
      headers: {
        "Content-type": "application/json",
      },
    });
    console.log(resp);
    setLoading(false);
  };
  useEffect(() => {
    if (!localStorage.getItem("tinder_api_key")) Router.push("/");
  }, []);
  return (
    <>
      <Head>
        <title>ChadBot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          Clicando no botão o bot vai começar uma conversa com todos os novos
          matches e vai responder todos os matches que estão na sua vez de
          responder. Seus cornos.
        </div>
        <button disabled={loading} onClick={() => chat()}>
          {loading ? "Enviando mensagens..." : "Enviar mensagens"}
        </button>
      </main>
    </>
  );
}
