import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import { sendCode } from '../tinder.js'

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [number, setNumber] = useState('+5531984635316');

  return (
    <>
    
      <Head>
        <title>ChadBot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h3>Número de celular associado ao Tinder</h3>
          <input value={number} type="text" onChange={(input) => {setNumber(input.target.value)}}/>
          <button onClick={() => sendCode(number)}>Enviar código</button>
        </div>
      </main>
    </>
  )
}
