import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";
import Router from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [phone, setNumber] = useState();
  const [code, setCode] = useState();

  const sendSms = async () => {
    await fetch("/api/send-sms", {
      method: "POST",
      body: JSON.stringify({
        phone: phone,
      }),
      headers: {
        "Content-type": "application/json",
      },
    });
  };

  const getToken = async () => {
    const resp = await fetch("/api/get-token", {
      method: "POST",
      body: JSON.stringify({
        phone: phone,
        code: code,
      }),
      headers: {
        "Content-type": "application/json",
      },
    });
    console.log("resp", resp);
    const response = await resp.json();
    console.log("response", response.meta);

    localStorage.setItem("tinder_api_key", response.data.api_token);
    if (response.data.api_token) Router.push("/main");
  };

  useEffect(() => {
    if (localStorage.getItem("tinder_api_key")) Router.push("/main");
  }, []);

  return (
    <>
      <Head>
        <title>ChadBot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.card}>
          <h3>
            Número de celular associado ao Tinder, formato: +5531999999999
          </h3>
          <input
            value={phone}
            type="text"
            onChange={(input) => {
              setNumber(input.target.value);
            }}
          />
          <button onClick={() => sendSms()}>Enviar código</button>
        </div>

        <div className={styles.card}>
          <h3>Código</h3>
          <input
            value={code}
            type="text"
            onChange={(input) => {
              setCode(input.target.value);
            }}
          />
          <button onClick={() => getToken()}>Entrar</button>
        </div>
      </main>
    </>
  );
}
